### ISSUE TITLE
There is no Copier function implemented for the OpenMM force type CustomBondForce

### ISSUE THREAD

**Issue by mkrompiec** [leeping/forcebalance#169]
Is such a copier even needed? If there are Harmonic bonds in the system, this function is executed anyway:
```
def CopyHarmonicBondParameters(src, dest):
    for i in range(src.getNumBonds()):
        dest.setBondParameters(i,*src.getBondParameters(i))

```
and it should (IMHO) copy parameters of all bonds, including custom.

**Comment by leeping** [comment]
I think you would need a copier for `CustomBondForce` if you have any bonds that use the `CustomBondForce` class. I haven't seen a use case for that so far, but it shouldn't be hard to implement.

**Comment by mkrompiec** [comment]
One important use case is for 1-4 non-bonded interactions which cannot be, for any reason, computed with the NonbondedForce. For example, if you have a CustomNonbondedForce and want to have 1-4 interactions scaled down.

**Comment by mkrompiec** [comment]
Hi Lee-Ping,
Could you please explain why are these copiers needed and what they
actually do? What happens if some parameters aren’t copied- are they
initialised to their original values from the input FF, or are they absent
from the FF at all? If I’m not fitting any parameters from, say,
CustomBondForce, can I get away with not having a copier?
Best,
Michal

**Comment by leeping** [comment]
Hello Michal,

> Could you please explain why are these copiers needed and what they  actually do? What happens if some parameters aren’t copied- are they initialised to their original values from the input FF, or are they absent from the FF at all?

The function of these Copiers is to set new parameters in your existing Simulation without needing to create a second Simulation, because that takes a few seconds and hurts performance.  First, the new System is created from the new force field XML. Next, the parameters from thew new System are copied to the existing Simulation.context.system. Finally, we call Simulation.context.system.getForce(i).updateParametersInContext(Simulation.context) to get the parameters into the GPU context and then the changes will be reflected in the computed energies.

If parameters aren't copied then they will be the same as the initial creation of the System (i.e. from the initial FF file).

> If I’m not fitting any parameters from, say, CustomBondForce, can I get away with not having a copier?

That is correct, if you do not have that Force in your OpenMM system, then you do not need to have a Copier function implemented for that object.

**Comment by mkrompiec** [comment]
Thanks Lee-Ping! Just one more thing to clarify:

> If I’m not fitting any parameters from, say, CustomBondForce, can I get
> away with not having a copier?
>
> That is correct, if you do not have that Force in your OpenMM system, then
> you do not need to have a Copier function implemented for that object.
>

I do have that force in my system, but I’m not fitting any parameters of
that force. Do i need the copier?

**Comment by leeping** [comment]
No, you would not need the copier in that case. If ForceBalance throws an error, then you could just write one that does nothing.

**Comment by mkrompiec** [comment]
Thanks a lot!
