### ISSUE TITLE
Gradient of potential w.r.t parameters 

### ISSUE THREAD

**Issue by adw62** [leeping/forcebalance#177]
Hi.

I'm interested in calculating gradients w.r.t force field parameters for thermodynamic integration.

Please may I ask. Does ForceBalance still calculate the gradient as described here? -> #95

Would the getEnergyParameterDerivatives function in OpenMM work for this purpose or are there disadvantages to this?

I would be interested in any input on this.

Thanks,
Alex

**Comment by leeping** [comment]
Hello Alex,

You are right, ForceBalance still calculates the parametric gradient of properties as in issue #95.  Thanks for the follow-up, as I hadn't seen your comment on the other thread.  

FB does not use `getEnergyParameterDerivatives`.  Instead it performs numerical finite difference on the force field parameters and evaluates the potential energy once for each parameter.  Using `getEnergyParameterDerivatives` may come with performance improvements, but I am also not sure if this has been implemented for all Forces.  Also, it would require some codes to map the force field parameter derivatives to context parameter derivatives (because the latter are generated from the former).

Thanks,

- Lee-Ping

**Comment by adw62** [comment]
Hi Lee-Ping,
    
Thanks for the reply, this is very helpful.

Cheers,
Alex
