### ISSUE TITLE
Feature request: Hydration free energy for Tinker

### ISSUE THREAD

**Issue by bdw2292** [leeping/forcebalance#208]
Hello,

I see there is a hydration.py and it is called by OpenMM engine. I am not super familiar with this code base yet, however it seems hydration.py is pretty "high level" and force field independent. So my question would be 1) how easy would it be to add for Tinker? and 2) What are all the code locations I would need to keep in mind when adding something like this?

**Comment by leeping** [comment]
Hello there,

hydration.py currently supports fitting the parameters of implicit solvent models only.  This is because implicit solvent makes the calculation of HFE easy, as one can easily compute the vertical energy gap between the liquid and gas phases.  With explicit solvent, this is more complicated as one needs to use more alchemical intermediates to turn off the solute/solvent interaction and soft core potentials are needed to prevent energy gaps from becoming infinitely large.  Explicit solvent hydration free energies have not been implemented in ForceBalance yet.

In light of the above, please let me know if this is something you're still interested in.

Thanks,

- Lee-Ping

**Comment by bdw2292** [comment]
Thank you for clarifying!

We are only interested in explicit simulations. I think we will stick with
just using our own hydration free energy computations for validation rather
than in the parameterization process.
