### ISSUE TITLE
TypeError : an integer is required

### ISSUE THREAD

**Issue by alexW432** [leeping/forcebalance#80]
Hi,
I have implemented a custom non bonded force into openMM and am now trying to optimize it with ForceBalance. However when run with my custom forcefeild and targets I get the error:
File "/usr/lib64/python-2.7/sitepackages/numpy/core/numeric.py", line 183, in ones 
a = empty(shape, dtype, order)
TypeError : an integer is required
This is the xml i'm using:
```Python
 <ForceField>
  <AtomTypes>
   <Type mass="15.99943" element="O" class="OW" name="tip3p-O"/>
   <Type mass="1.007947" element="H" class="HW" name="tip3p-H"/>
  </AtomTypes>
  <Residues>
   <Residue name="HOH">
    <Atom name="O" type="tip3p-O"/>
    <Atom name="H1" type="tip3p-H"/>
     <Atom name="H2" type="tip3p-H"/>
     <Bond to="1" from="0"/>
     <Bond to="2" from="0"/>
   </Residue>
  </Residues>
  <HarmonicBondForce>
   <Bond k="462750.4" length="0.09572" class2="HW" class1="OW"/>
  </HarmonicBondForce>
  <HarmonicAngleForce>
   <Angle k="836.8" class2="OW" class1="HW" angle="1.82421813418" class3="HW"/>
  </HarmonicAngleForce>
  <NonbondedForce lj14scale="0.5" coulomb14scale="0.833333">
   <Atom type="tip3p-O" epsilon="0" sigma="0" charge="-0.834"/>
   <Atom type="tip3p-H" epsilon="0" sigma="0" charge="0.417"/>
  </NonbondedForce>
  <BuckinghamForce bondCutoff="3" energy="B1*B2*(eps/(1-(6/gamma)))*((6/gamma)*exp(gamma*(1-r/sig))-((sig/r)^6)); sig=sqrt(sig1*sig2); gamma=sqrt(gamma1*gamma2); eps=sqrt(eps1*eps2)">
   <PerParticleParameter name="B"/>
   <PerParticleParameter name="eps"/>
   <PerParticleParameter name="sig"/>
   <PerParticleParameter name="gamma"/>
   <Atom type="tip3p-O" parameterize="eps,sig,gamma" gamma="12.75" sig="3.55e-1" eps="0.65" B="1"/>
   <Atom type="tip3p-H" gamma="1" sig="1" eps="1" B="0"/>
  </BuckinghamForce>
 </ForceField>
```
my only targets are gas and liquid pdb from forcebalance/studies/005_iamoeba/targets and a data.csv with:
```Python
T	      P	   MBAR	     Rho   Rho_w  Hvap  Hvap_wt
298.15	1.0 atm	TRUE	997.045	1	43.989	1
```
I'm not sure what is causing this error other examples in the studies directory seem to work fine, any help would be greatly appreciated.
Many Thanks,
Alex

**Comment by alexW432** [comment]
Also the file.in is use is 
```Python
$options
forcefield ForceB.xml
jobtype newton
$end
$target
type Liquid_OpenMM
name WATER
$end
```
Where WATER contains the two pdbs and the data.csv. Again thank you.
Alex

**Comment by leeping** [comment]
Hi Alex,

Thanks for the error report.  I'll take a look.

- Lee-Ping

**Comment by leeping** [comment]
Hi Alex,

I fixed the issue you were seeing on the master branch.  It only shows up when there's just one phase point (T,P) with `MBAR = True` in data.csv.  When MBAR is applied to just one phase point, it's the same as not applying MBAR at all, so I just made that change in your code and it gets past that error.

There are a couple more issues.

1) You need to rename your `BuckinghamForce -> CustomNonbondedForce`.  Otherwise, these parameters aren't being used at all and the simulation explodes.

2) OpenMM will refuse to create the `System` because `nonbondedMethod = PME` is the default setting that ForceBalance passes to `forcefield.createSystem()`, and this setting is incompatible with `CustomNonbondedForce`.  However, we actually want PME for the electrostatics which is described using the regular `NonbondedForce`.  

I think one possible solution would be to call `createSystem(nonbondedMethod=cutoffPeriodic)` and then set `nonbondedMethod = PME` for just the `NonbondedForce`.  I would just have to pass the PME parameters to `NonbondedForce` in a way that's consistent with how `forcefield.createSystem()` does it.

@peastman: Do you agree with my above solution for passing different `nonbondedMethod`s to `CustomNonbondedForce` and `NonbondedForce`?  If you agree, what are the default PME parameters to `NonbondedForce` used by `forcefield.createSystem()`?  If you don't agree, do you think there's a better way to do it?

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
I'm not sure what your question is.  If you want PME for NonbondedForce and CutoffPeriodic for CustomNonbondedForce, then yes, what you said would work.

**Comment by leeping** [comment]
Thanks, that was my question. My other question was concerning whether I would need to call functions such as `setEwaldErrorTolerance()` and `setPMEParameters()` in order to get behavior that is consistent with `forcefield.createSystem(nonbondedMethod=PME)`

**Comment by peastman** [comment]
If you specify ewaldErrorTolerance in your call to createSystem(), it will call setEwaldErrorTolerance() with that value.  Otherwise, it will keep the default value.  setPMEParameters() is only used if you want to override the standard mechanism for selecting parameters.

**Comment by leeping** [comment]
Thanks, Peter.  I understand now.  :)

**Comment by leeping** [comment]
@alexW432 : I implemented the change in OpenMM where the system is created with `nonbondedMethod=CutoffNonPeriodic` and it calls `force.setNonbondedMethod(force.PME)` later for `NonbondedForce` and `AmoebaMultipoleForce`.  This should allow you to do your calculation.  The new code is here, along with some stuff that allows you to set the nonbonded and vdW cutoffs from the input file: https://github.com/leeping/forcebalance/pull/81

A few notes: 1) You need to rename `BuckinghamForce` -> `CustomNonbondedForce` for it to be recognized.  

2) Your setting of gamma=12.75 was not repulsive enough, since I saw that the system was still blowing up.  I tried setting gamma=15.0 and it worked.  

3) Since the Buckingham potential goes to negative infinity at small r, you might like to try the alternate functional form I derived some time ago, described in this paper:

http://dx.doi.org/10.1021/ct300826t

<img width="385" alt="screenshot 2015-07-13 20 22 34" src="https://cloud.githubusercontent.com/assets/1441560/8665789/f1722902-299c-11e5-963e-9d6ac88dea1e.png">

@peastman : Does your answer also apply to aEwald and pmeGridDimensions for the AmoebaMultipoleForce? 

That is, if I call createSystem(nonbondedMethod=CutoffPeriodic, aEwald=Something, pmeGridDimensions=SomethingElse) and then I call AmoebaMultipoleForce.setNonbondedMethod(PME), will it keep the aEwald and pmeGridDimensions that I had from before?

**Comment by alexW432** [comment]
This works great, thank you so much. Since I’m using a non-polarized model do I need to add a correction to the heat of vaporization or does force balance anticipate this and add it. Additionally if force balance does add the correction and I allowed the charges and angles to vary during optimization does force balance recalculate this correction? If not would it be possible for me to add this calculation. 
Thank you.
Alex

**Comment by leeping** [comment]
Hi Alex,

If you use the options `self_pol_mu0` and `self_pol_alpha` as I have done in the example 007_tip4p_STP, then ForceBalance will calculate the correction for you.

The code for the polarization correction is found at line 345 in liquid.py - you can see it does the minimization for you, so it should reflect the impact of changing the bond and angle parameters.

```
    def polarization_correction(self,mvals):
        self.FF.make(mvals)
        # print mvals                                                                                                                                                                                       
	ddict = self.gas_engine.multipole_moments(optimize=True)['dipole']
        d = np.array(ddict.values())
        if not in_fd():
	    logger.info("The molecular dipole moment is % .3f debye\n" % np.linalg.norm(d))
	# Taken from the original OpenMM interface code, this is how we calculate the conversion factor.                                                                                                    
        # dd2 = ((np.linalg.norm(d)-self.self_pol_mu0)*debye)**2                                                                                                                                            
        # eps0 = 8.854187817620e-12 * coulomb**2 / newton / meter**2                                                                                                                                        
        # epol = 0.5*dd2/(self.self_pol_alpha*angstrom**3*4*np.pi*eps0)/(kilojoule_per_mole/AVOGADRO_CONSTANT_NA)                                                                                           
	# In [2]: eps0 = 8.854187817620e-12 * coulomb**2 / newton / meter**2                                                                                                                                
        # In [7]: 1.0 * debye ** 2 / (1.0 * angstrom**3*4*np.pi*eps0) / (kilojoule_per_mole/AVOGADRO_CONSTANT_NA)                                                                                           
        # Out[7]: 60.240179789402056                                                                                                                                                                        
        convert = 60.240179789402056
        dd2 = (np.linalg.norm(d)-self.self_pol_mu0)**2
	epol = 0.5*convert*dd2/self.self_pol_alpha
        return epol
```

However, I can anticipate a problem you will have in parameterizing the geometry of a *rigid* water model: ForceBalance cannot differentiate the thermodynamic properties with respect to the bond and angle parameters because the energy is not written as an explicit function of these parameters (rather, the constrained positions are determined by an algorithm which depends on the simulation software).  

In my paper at http://dx.doi.org/10.1021/jz500737m , I used a trick where I placed all of the interaction sites on virtual sites whose positions are precisely controlled by the parameters.  At the conclusion of the parameterization, I re-made the force field file by placing the atoms at the virtual sites and eliminating the virtual sites.

Thanks,

- Lee-Ping

**Comment by alexW432** [comment]
Thank you :). For self_pol_mu0 1.855 and self_pol_alpha 1.470 what units did you use? would these values be applicable to tip3p?

**Comment by leeping** [comment]
Yes, these values would apply for TIP3P.  The units are Debye and Angstrom^3.

**Comment by alexW432** [comment]
Thanks alot, this really helped me out :)
Alex

**Comment by leeping** [comment]
No problem! Let me know if you have any more questions.
